create table Answers (answerIdk bigint, answerNo bigint, answerYes bigint, question_id bigint not null, gift_id bigint not null, primary key (gift_id, question_id))
create table Gift (id bigint generated by default as identity (start with 1), description varchar(255), likes bigint, name varchar(255) not null, url varchar(255) not null, primary key (id))
create table Question (id bigint generated by default as identity (start with 1), question varchar(255) not null, primary key (id))
alter table Gift add constraint UK_uniqUrl unique (url)
alter table Question add constraint UK_uniqQuestion unique (question)
alter table Answers add constraint FK_question foreign key (question_id) references Question on delete cascade
alter table Answers add constraint FK_gift foreign key (gift_id) references Gift on delete cascade